apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapps-platform-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - clusters: {}
  template:
    metadata:
      name: sampleapps-platform-dev
    spec:
      project: default
      source:
        repoURL: {{cookiecutter.repo}}
        targetRevision: develop
        path: examples/linux-basic/argo_workloads/sampleapps
        directory:
          recurse: true
      destination:
        namespace: 'sampleapps'
        name: "{{ .name }}"
